tasks:
  - name: App
    init: >
      npm &&
      gp sync-done install
    command: REACT_APP_PROVIDER=$(gp url 8545) npm start
  - name: Chain
    init: gp sync-await install
    command: npm chain
    openMode: split-right
  - name: Deployment
    init: gp sync-await install
    command: npm deploy
    openMode: split-right
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8545
    onOpen: ignore
github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - juanblanco.solidity
