name: Deploy PROD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Deploy a specific commit by hash (optional)
      accept:
        type: string
        description: Confirm by typing "deploy to prod"
        required: true
jobs:
  deploy:
    if: github.event.inputs.accept == 'deploy to prod'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm run build:prod
    - name: Deploy over FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        # ftp server
        server: ${{ secrets.SERVER_ADDRESS }}
        # ftp username
        username: ${{ secrets.SERVER_USERNAME }}
        # ftp password
        password: ${{ secrets.SERVER_PASSWORD }}
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftps
        # Folder to upload from, must end with trailing slash /
        local-dir: build/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: /app.hectordao.com/
        # Prints which modifications will be made with current config options, but doesnt actually make any changes
        dry-run: false
        # Deletes ALL contents of server-dir, even items in excluded with exclude argument
        dangerous-clean-slate: false
        # An array of glob patterns, these files will not be included in the publish/delete process
        # exclude:
        # How verbose should the information be - minimal, standard, or verbose
        log-level: standard
        # strict or loose
        security: loose
